### ISSUE TITLE
PDF Uncertainty Weights

### ISSUE THREAD

**Issue by amarini** [MiT-HEP/NeroProducer#146]
* save pdf weights for uncertainty computation 
   weights()[1,2,3,4,6,8]

**Comment by yiiyama** [comment]
Those only deal with mu_R and mu_F. We also need PDF variations, even though full implementation of the PDF4LHC recommendation is not possible at the moment.
CMS recommendation https://indico.cern.ch/event/459797/contribution/2/attachments/1181555/1710844/mcaod-Nov4-2015.pdf is to use NNPDF 3.0 variations.
100 floats (or 60 if we decide to use the MC replicas -> eigenvector variations converter mentioned in the slides above) is a lot from the perspective of file size. Since we use this information only in specific cases, it may make sense to store these numbers in a separate file and use AddFriend from the main tree whenever required. It does sound error prone, but I've done something similar before with no problem.

**Comment by amarini** [comment]
If these needs to be used to implement the prescription from the PDF4LHC recomendation, I'm afraid there is no way to avoid it. 
I would try to keep everything in one file, in order to avoid to ship multiple files.
I would not save all the individual weights in the all-tree but rather only the sum in an histogram like [this](https://github.com/MiT-HEP/NeroProducer/blob/master/Nero/plugins/Nero.cc#L339) (with the right number of bins )

**Comment by yiiyama** [comment]
Just for record: I agree with all the above.

**Comment by amarini** [comment]
#149
