### ISSUE TITLE
Branch prefixes

### ISSUE THREAD

**Issue by yiiyama** [MiT-HEP/NeroProducer#190]
I have not followed recent developments regarding the branch naming (cachedPrefix??). It does seem to me that the defineBranches and setBranchAddresses functions with prefix as the second argument are now obsolete and can be removed. In fact there are compiler warnings from hidden overrides etc.

Could anyone who made the recent change comment on this?

**Comment by amarini** [comment]
I also don't like the asymmetry between setBranchAddress ( prefix)  and defineBranches () { ... cached Prefix.

**Comment by sidnarayanan** [comment]
Hi, it was me that made the changes. Basically, because we have multiple fat jet collections, we needed a way of distinguishing the branch names. Because of the way [1] is written, I didn't want defineBranches() to have an additional argument defining the branch name. We can of course change setBranchAddress() to not take a prefix argument anymore, but I figured this would be easier to use when reading a tree than setting cachedPrefix and then calling setBranchAddress. 

That being said, it would probably be a good idea to clean up any unused functions.

[1] https://github.com/MiT-HEP/NeroProducer/blob/master/Nero/plugins/Nero.cc#L432-L433
